// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFMPEG() {
  return window['go']['main']['App']['CheckFFMPEG']();
}

export function Download(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3, arg4, arg5);
}

export function GetDirectory() {
  return window['go']['main']['App']['GetDirectory']();
}

export function GetImportantInfo(arg1) {
  return window['go']['main']['App']['GetImportantInfo'](arg1);
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}
