// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Download(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<boolean>;

export function GetDirectory():Promise<string|boolean>;

export function GetImportantInfo(arg1:string):Promise<main.Info>;
